### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by caneraydinbey** [florind/spring-boot-rfc6902#1]
I imported to intellj. then clicked run but lots of errors. why no pomxml?

errors:

> Information:Using javac 1.8.0_77 to compile java sources
> Information:java: Errors occurred while compiling module 'main'
> Information:Module "main" was fully rebuilt due to project configuration/dependencies changes
> Information:20.04.2016 15:36 - Compilation completed with 35 errors and 0 warnings in 5s 704ms
> /home/caneraydin/IdeaProjects/spring-boot-rfc6902/src/main/java/com/newsplore/repository/PolicyBundleRepository.java
> Error:(4, 47) java: package org.springframework.data.jpa.repository does not exist
> Error:(5, 53) java: package org.springframework.data.rest.core.annotation does not exist
> Error:(8, 50) java: cannot find symbol
>   symbol: class JpaRepository
> Error:(7, 2) java: cannot find symbol
>   symbol: class RepositoryRestResource
> /home/caneraydin/IdeaProjects/spring-boot-rfc6902/src/main/java/com/newsplore/domain/PolicyBundle.java
> Error:(3, 40) java: package com.fasterxml.jackson.annotation does not exist
> Error:(4, 40) java: package com.fasterxml.jackson.annotation does not exist
> Error:(5, 40) java: package com.fasterxml.jackson.annotation does not exist
> Error:(6, 49) java: package com.fasterxml.jackson.databind.annotation does not exist
> Error:(7, 49) java: package com.fasterxml.jackson.databind.annotation does not exist
> Error:(8, 1) java: package lombok does not exist
> Error:(9, 51) java: package org.springframework.data.jpa.domain.support does not exist
> Error:(11, 1) java: package javax.persistence does not exist
> Error:(12, 24) java: package javax.validation does not exist
> Error:(13, 36) java: package javax.validation.constraints does not exist
> Error:(15, 2) java: cannot find symbol
>   symbol: class Data
> Error:(16, 2) java: cannot find symbol
>   symbol: class JsonInclude
> Error:(17, 2) java: cannot find symbol
>   symbol: class JsonIgnoreProperties
> Error:(18, 2) java: cannot find symbol
>   symbol: class EntityListeners
> Error:(19, 2) java: cannot find symbol
>   symbol: class Entity
> Error:(20, 2) java: cannot find symbol
>   symbol: class NoArgsConstructor
> Error:(30, 6) java: cannot find symbol
>   symbol:   class Getter
>   location: class com.newsplore.domain.PolicyBundle
> Error:(30, 14) java: cannot find symbol
>   symbol:   class Setter
>   location: class com.newsplore.domain.PolicyBundle
> Error:(31, 6) java: cannot find symbol
>   symbol:   class NoArgsConstructor
>   location: class com.newsplore.domain.PolicyBundle
> Error:(31, 25) java: cannot find symbol
>   symbol:   class AllArgsConstructor
>   location: class com.newsplore.domain.PolicyBundle
> Error:(32, 6) java: cannot find symbol
>   symbol:   class Embeddable
>   location: class com.newsplore.domain.PolicyBundle
> Error:(23, 6) java: cannot find symbol
>   symbol:   class Id
>   location: class com.newsplore.domain.PolicyBundle
> Error:(23, 10) java: cannot find symbol
>   symbol:   class GeneratedValue
>   location: class com.newsplore.domain.PolicyBundle
> Error:(24, 6) java: cannot find symbol
>   symbol:   class JsonIgnore
>   location: class com.newsplore.domain.PolicyBundle
> Error:(27, 6) java: cannot find symbol
>   symbol:   class Embedded
>   location: class com.newsplore.domain.PolicyBundle
> Error:(27, 16) java: cannot find symbol
>   symbol:   class Valid
>   location: class com.newsplore.domain.PolicyBundle
> Error:(38, 10) java: cannot find symbol
>   symbol:   class NotNull
>   location: class com.newsplore.domain.PolicyBundle.Payment
> /home/caneraydin/IdeaProjects/spring-boot-rfc6902/src/main/java/com/newsplore/Application.java
> Error:(3, 32) java: package org.springframework.boot does not exist
> Error:(4, 46) java: package org.springframework.boot.autoconfigure does not exist
> Error:(6, 2) java: cannot find symbol
>   symbol: class SpringBootApplication
> Error:(9, 9) java: cannot find symbol
>   symbol:   variable SpringApplication
>   location: class com.newsplore.Application

**Comment by florind** [comment]
It's a gradle project. Use the command line `./gradlew test` to issue the test.
